version: '3'

services:

  dockernode:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app

  
  mysql:
      container_name: Container_mysql
      hostname: mysql
      image: mysql
      restart: always
      command:
        - --default-authentication-plugin=mysql_native_password
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --innodb_force_recovery=0
      volumes: 
        - C:\Users\Gabriel\Desktop\MySQL_API:/var/lib/mysql
      ports:
        - 3306:3306
      environment:
<<<<<<< HEAD
        MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
=======
        MYSQL_ROOT_PASSWORD: gabriel123
        MYSQL_DATABASE: API_REST
        MYSQL_USER: gabriel
        MYSQL_PASSWORD: gabriel123
>>>>>>> e67e266d4808d6838be9e418800ff5768780f93d
        TZ: America/Sao_Paulo